### PR TITLE
替换各种文件的图标

### PR DESCRIPTION
**Pull request by feizhen**

### CODE REVIEW

**Comment by whitesslily** [comment]
replace all kinds of icon of paper? it is icon in the theme ?

**Comment by jamiewilson** [comment]
Hey, sorry for taking so long to look at this. Unfortunately I don't think I am going to merge this.

I really would like to improve the breadth of file icon support, but there are two things that would need to be addressed with this:

1. I think I would prefer having white icons rather than all the different colors
2. Even though there are @2x images, they still seem really fuzzy 

| Proposed  | Current     |  
| ---------- | ---------- |
| screen shot 2016-11-08 at 17 09 14 | screen shot 2016-11-08 at 17 10 30

If you are still interested in working on this, it might be helpful to take a look at the current icon source files: https://github.com/jamiewilson/predawn-icons

I'm not saying that all the icons _need_ to be custom, but the more consistent and crisp they can be the better. 

Let me know if you have any questions. And again, sorry it took so long. Thanks for the patience.

**Comment by jrnewell** [comment]
If anyone is looking for colored icons to use with this theme, you can use this package (https://github.com/ihodev/a-file-icon) and get it for free

**Comment by jamiewilson** [comment]
Hey @feizhen, I appreciate the work on this, but I think I'm going to suggest people take a look at https://github.com/ihodev/a-file-icon instead of baking it into Predawn. Let me know if you think of any other improvements.

**Pull request closed without merging**
