### PR TITLE
Adds support for optionally showing disclosure arrow buttons

### PR DESCRIPTION
**Pull request by wolthers**
The theme currently doesn't support recursively opening or -closing folders by `cmd`+`shift`-clicking the disclosure arrows next to the folders (because they're hidden in the theme). This PR adds an **optional** setting to show the arrows. It is not to be confused with the `predawn_sidebar_arrows` option, which essentially just replaces the folder icon with an arrow icon as `cmd`+`shift`-clicking these doesn't do anything.
###### Changes made:
- Made new disclosure arrow icons with same stroke width as the file type icons
- Remade the close-file icon to match the thickness of the above icon
- Documented the new option in README.md
- Moved folder icons (@2x versions only) up 1 px to better align with the file name. Didn't need to change the 1x versions as they were already correctly placed
###### Screenshots:

With `Show open files` **disabled**
image

With `Show open files` **enabled**
image

### CODE REVIEW

**Comment by jamiewilson** [comment]
Well done! Thanks for the help. I'll try to pull these down today and let you know if I have any questions/feedback before merging.

**Comment by wolthers** [comment]
You're welcome, thought i'd share it. Let me know if anything is missing!

**Comment by wolthers** [comment]
@jamiewilson: Any comments thus far?

**Comment by jamiewilson** [comment]
Unfortunately, no. Haven't had a chance to look at it yet but I should be able to this week. I'll keep you posted.

**Comment by wolthers** [comment]
Ping :)

**Comment by jamiewilson** [comment]
Hey man, thanks for the reminder! I'm really sorry, but I've got some other things taking priority over this right now. But it shouldn't be too much longer!

**Comment by jamiewilson** [comment]
Hey man, I made a small change to this PR: hiding disclosure icons when `predawn_sidebar_narrow: true` is set.

https://github.com/jamiewilson/predawn/commit/dbf6a9fb2e5fa9ba10dbb4f76b93933d908e36c1

If this looks good to you, I'll go ahead and merge to master. Thanks for your patience with this. Sorry it took so long.

**Comment by jamiewilson** [comment]
Hey @wolthers. Wanted to make sure you saw this.

**Pull request closed without merging**
